apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctf-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: ctf
  template:
    metadata:
      labels:
        app: ctf
    spec:
      restartPolicy: Always
      containers:
        - name: ctf
          image: ctfd/ctfd
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /var
              name: ctf-data
          env:
            - name: UPLOAD_FOLDER
              value: /var/uploads
            - name: LOG_FOLDER
              value: /var/log/CTFd
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ctf-secret
                  key: dbURL
          ports:
            - containerPort: 8000
      volumes:
          - name: ctf-data
            persistentVolumeClaim:
              claimName: ctf-app-pvc