apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.TwentyFortyEight.name }}-svc
spec:
  selector:
    app: {{ .Values.TwentyFortyEight.name }}
  ports:
  - port: 80
    targetPort: 80
    name: port-80
  - port: 22
    targetPort: 22
    name: port-22
  clusterIP: None
---
{{- $root := . -}}
{{ $count :=  ( .Values.numberOfTeams | int) }}
{{- range untilStep 0 $count 1 }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $root.Values.TwentyFortyEight.name }}-svc-{{ . }}"
  labels:
    app: "{{ $root.Values.TwentyFortyEight.name }}-svc-{{ . }}"
spec:
  ports:
  - port: 80
    targetPort: 80
    name: port-80
  - port: 22
    targetPort: 22
    name: port-22
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: "{{ $root.Values.TwentyFortyEight.name }}-{{ . }}"
---
{{- end }}