{{- $root := . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.TwentyFortyEight.name }}-svc
spec:
  selector:
    app: {{ .Values.TwentyFortyEight.name }}
  ports:
  {{ $count :=  ( add 10 .Values.numberOfTeams | int) }}
  {{- range untilStep 10 $count 1 }}
    - port: 80{{ . }}
      targetPort: 80{{ . }}
      name: port-80{{ . }}
    - port: 22{{ . }}
      targetPort: 22{{ . }}
      name: port-22{{ . }}
  {{- end }}
  type: {{ .Values.TwentyFortyEight.service.type }}