apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ctfd.labels }}-svc
spec:
  selector:
    app: {{ .Values.ctfd.labels }}
  ports:
  - port: {{ .Values.ctfd.service.port }}
    targetPort: 8000
  type: {{ .Values.ctfd.service.type }}
