apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mariadb.storage.pvc }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: {{ .Values.mariadb.storage.size }}