apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hodor.name }}
spec:
  replicas: {{ .Values.hodor.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Values.hodor.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.hodor.name }}
    spec:
      restartPolicy: {{ .Values.hodor.restartPolicy }}
      containers:
        - name: {{ .Values.hodor.name }}
          image: {{ .Values.hodor.image }}
          resources:
            limits:
              memory: "256Mi"
          ports:
            - containerPort: 1337
          imagePullPolicy: Always