apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hodor.name }}-svc
spec:
  selector:
    app: {{ .Values.hodor.name }}
  ports:
  - port: {{ .Values.hodor.service.port }}
    targetPort: {{ .Values.hodor.service.targetPort }}
  type: ClusterIP
