{{- $root := . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jail.name }}-svc
spec:
  selector:
    app: {{ .Values.jail.name }}
  ports:
  {{ $count :=  ( add 10 .Values.numberOfTeams | int) }}
  {{- range untilStep 10 $count 1 }}
    - port: 70{{ . }}
      targetPort: 7007
      name: port-7007{{ . }}
  {{- end }}
  type: {{ .Values.jail.service.type }}