apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jail.name }}-svc
spec:
  selector:
    app: {{ .Values.jail.name }}
  ports:
  - port: 7007
    targetPort: 7007
    name: port-7007
  clusterIP: None
---
{{- $root := . -}}
{{ $count :=  ( .Values.numberOfTeams | int) }}
{{- range untilStep 0 $count 1 }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $root.Values.jail.name }}-svc-{{ . }}"
  labels:
    app: "{{ $root.Values.jail.name }}-svc-{{ . }}"
spec:
  ports:
  - port: 7007
    targetPort: 7007
    name: port-7007
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: "{{ $root.Values.jail.name }}-{{ . }}"
---
{{- end }}