apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jail.name }}-svc
spec:
  selector:
    app: {{ .Values.jail.name }}
  ports:
  - port: {{ .Values.jail.service.port }}
    targetPort: {{ .Values.jail.service.targetPort }}
  type: {{ .Values.jail.service.type }}
