apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.path.name }}
spec:
  replicas: {{ .Values.path.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Values.path.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.path.name }}
    spec:
      restartPolicy: {{ .Values.path.restartPolicy }}
      containers:
        - name: {{ .Values.path.name }}
          image: {{ .Values.path.image }}
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 80