apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.4.12
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
          envFrom:
            - secretRef:
                name: ctf-db-env
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 3306
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: ctf-db-pvc
