# Number of Participants teams/players
numberOfTeams: 2

global:
  # Number of Participants teams/players
  numberOfTeams: 2
  TwentyFortyEight:
    name: twentyfortyeight
  jail:
    name: jail
  hodor:
    name: hodor
  path:
    name: path-not-taken

ctfd:
  name: ctf-app
  labels: ctf
  replicas: 1
  restartPolicy: Always
  image: ctfd/ctfd
  storageSize: 30Gi
  secretName: ctf-secret
  service:
    type: ClusterIP
    port: 8000

mariadb:
  name: mariadb
  image: mariadb:10.4.12
  secretName: ctf-db-env
  storage:
    volume: db-data
    pvc: ctf-db-pvc
    size: 40Gi
  service:
    name: db-svc

hodor:
  name: hodor
  labels: hodor
  replicas: 3
  restartPolicy: Always
  image: galbirk/hodor:latest
  service:
    type: ClusterIP
    port: 1337
    targetPort: 1337

path:
  name: path-not-taken
  labels: path
  replicas: 1
  restartPolicy: Always
  image: galbirk/path:latest
  service:
    type: ClusterIP
    port: 80
    targetPort: 80

TwentyFortyEight:
  name: twentyfortyeight
  replicas: 1
  restartPolicy: Always
  image: galbirk/twentyfortyeight:latest
  service:
    name: twentyfortyeight
    type: ClusterIP
    port: 80
    targetPort: 80


jail:
  name: jail
  labels: jail
  replicas: 1
  restartPolicy: Always
  image: galbirk/jail:latest
  service:
    name: jail
    type: LoadBalancer
    port: 7007
    targetPort: 7007

ingress-nginx: 
  tcp: 
    8000: "default/test-svc:80"
