ctfd:
  name: ctf-app
  labels: ctf
  replicas: 1
  restartPolicy: Always
  image: ctfd/ctfd
  storageSize: 30Gi
  secretName: ctf-secret
  service:
    type: LoadBalancer
    port: 80

mariadb:
  name: mariadb
  image: mariadb:10.4.12
  secretName: ctf-db-env
  storage:
    volume: db-data
    pvc: ctf-db-pvc
    size: 40Gi
  service:
    name: db-svc

hodor:
  name: hodor
  labels: hodor
  replicas: 1
  restartPolicy: Always
  image: galbirk/hodor:latest
  service:
    type: LoadBalancer
    port: 1337
    targetPort: 1337

path:
  name: path-not-taken
  labels: path
  replicas: 1
  restartPolicy: Always
  image: galbirk/path:latest
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80

TwentyFortyEight:
  name: twentyfortyeight
  numberOfTeams: 4
  replicas: 1
  restartPolicy: Always
  image: galbirk/twentyfortyeight:latest
  service:
    name: twentyfortyeight
    type: LoadBalancer
    port: 80
    targetPort: 80




